### PR TITLE
update Alpine base image version

### PR DESCRIPTION
**Pull request by riccardomodanese**
Upgraded the Alpine base image version.
The old version caused tests on M1 to hang up.

Signed-off-by: riccardomodanese <riccardo.modanese@eurotech.com>

### CODE REVIEW

**Comment by riccardomodanese** [comment]
@elbert3 can you build the container, tag (is 0.4.0 the last version? so 0.4.1 or 0.5.0?) and push it to our repo? thanks!

**Review by elbert3 — APPROVED** [review]

**Comment by elbert3** [comment]
@riccardomodanese - I merged this PR and #3 that had some of my other changes.  I tagged it as 0.6.0 (there was already a 0.5.0) and pushed my locally built image to the repo.

**Comment by riccardomodanese** [comment]
I was receiving error while trying to pull the image:
docker pull eurotech/dummy-webserver:0.6.0
Error response from daemon: manifest for eurotech/dummy-webserver:0.6.0 not found: manifest unknown: manifest unknown

looking at the docker hub web ui it seems that the last tag is still the 0.5.0. Could you try again to tag and publish the container?
Thanks!

https://hub.docker.com/r/eurotech/dummy-webserver/tags

**Comment by elbert3** [comment]
I pushed it to the eurotech repo, not the public docker one.  Try:  `docker pull public.ecr.aws/eurotech-dev/dummy-webserver:0.6.0`

**Pull request merged**
